### ISSUE TITLE
upload to app store fail

### ISSUE THREAD

**Issue by melon8** [yidun/captcha-ios-demo#1]
我pod update 'VerifyCode'，然后打包upload到appstore上后，提示失败，并收到以下邮件
Missing Code Signing Entitlements - No entitlements found in bundle 'NetEase.NTESVerifyCodeResources' for executable 'Payload/xxx.app/NTESVerifyCodeResources.bundle/NTESVerifyCodeResources'."

Invalid Bundle Structure - The binary file 'YoudaoCourse.app/NTESVerifyCodeResources.bundle/NTESVerifyCodeResources' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide for information on the iOS app bundle structure.
请问我该怎么操作呢

**Comment by skylinchen** [comment]
你好！
不好意思，今天才看到邮件。麻烦再重新  "pod update"  一下





在 2018-01-25 17:54:02，"melon8" <notifications@github.com> 写道：


我pod update 'VerifyCode'，然后打包upload到appstore上后，提示失败，并收到以下邮件
Missing Code Signing Entitlements - No entitlements found in bundle 'NetEase.NTESVerifyCodeResources' for executable 'Payload/xxx.app/NTESVerifyCodeResources.bundle/NTESVerifyCodeResources'."

Invalid Bundle Structure - The binary file 'YoudaoCourse.app/NTESVerifyCodeResources.bundle/NTESVerifyCodeResources' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide for information on the iOS app bundle structure.
请问我该怎么操作呢
